export const LANDING_ROUTE = '/'
export const CONFIRM_ROUTE = '/confirm'
export const LOGIN_ROUTE = '/login'
export const SUCCESS_ROUTE = '/checkoutsuccess'
export const ADMIN_ROUTE = '/admin'
export const ASSISTANT_BOOK = '/assistantt/mylibrary'
export const ASSISTANT_COURSE = '/assistantt/mycourses'
