import Cell from "./Cell";
export default function Table(){
    return (
        <div className="grid grid-cols-8 border gap-0 mt-6">
            <Cell text="Время/Дни недели"/>
            <Cell text="Пн"/>
            <Cell text="Вт"/>
            <Cell text="Ср"/>
            <Cell text="Чт"/>
            <Cell text="Пт"/>
            <Cell text="Сб"/>
            <Cell text="Вс"/>
            <Cell text="9:00 - 10:00"/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text="10:00 - 11:00"/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text="11:00 - 12:00"/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text="12:00 - 13:00"/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text="13:00 - 14:00"/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text="14:00 - 15:00"/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell disabled text="15:00 - 16:00"/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text="16:00 - 17:00"/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text=""/>
            <Cell text=""/>
        </div>
    );
}